FROM elixir:1.4.5 

RUN mix local.hex --force && \ 
    mix local.rebar --force && \ 
    mix hex.info

COPY ./mix.exs ./mix.lock ./ 
RUN mix deps.get

COPY ./web/ ./web/
COPY ./lib/ ./lib/
COPY ./config/ ./config/
COPY ./test/ ./test/
COPY ./priv/ ./priv/
COPY ./rel/config.exs ./rel/config.exs

ENV MIX_ENV=prod
RUN mix release

RUN pwd 

